On Android, allow PRAGMA statements that assign when invoked via `exec`
craftzdog/react-native-sqlite-2 pull request #99
Opened 2021-05-18 08:57 UTC by ilmoraunio

Fixes the following error on Android

```
{"error": {"error": [Error: unknown error (code 0): Queries can be performed using SQLiteDatabase query or rawQuery methods only.], "insertId": undefined, "rows": undefined, "rowsAffected": undefined}}
```

when accessing `exec` directly to try to run assigning PRAGMA statements, such as `PRAGMA journal_mode = WAL`.

2021-05-22 02:49 UTC, craftzdog commented
Would you add some tests to https://github.com/craftzdog/react-native-sqlite-2/blob/master/test/app.js?

2021-05-27 09:34 UTC, ilmoraunio commented
Ah, will add.

2021-07-01 14:18 UTC, ilmoraunio commented
Added some tests and also tested them on Android & iOS.

2021-07-05 06:02 UTC, craftzdog requested changes
Thanks! Can you fix them?

2021-07-05 06:02 UTC, craftzdog commented on test/app.js
> +        journal_mode = result[0].rows[0].journal_mode
Add `const` or it causes `ReferenceError`

2021-07-05 06:02 UTC, craftzdog commented on test/app.js
> +        row = result[0].rows[0]
Add `const` or it causes `ReferenceError`

2021-08-05 07:07 UTC, merged